#!/usr/bin/python
# Generate Othello.5.gen, Pylos.5.gen, Checkers.5.gen (testPlay)
# Generate Othello.6.gen, Pylos.6.gen, Checkers.6.gen (testRun)

import os
import sys

games = ['Othello', 'Pylos', 'Checkers']
playIters = [180, 60, 115]
runIters = [240, 60, 130]

for i in xrange(len(games)):
  with open('%s.5.gen' % games[i], 'w') as genfile:
    genfile.write('# Play a bunch of games, automatically generated by '
                  'gen-random-games.py\n')
    for seed in xrange(playIters[i]):
      genfile.write('testPlay %s 500\n' % seed)
      genfile.write('showAll\n')
      genfile.write('undoLastMove 500\n\n')

    genfile.write('quit\n')

  with open('%s.6.gen' % games[i], 'w') as genfile:
    genfile.write('# Run a bunch of games, automatically generated by '
                  'gen-random-games.py\n')
    for seed in xrange(runIters[i]):
      genfile.write('testRun %s 50\n' % seed)
      genfile.write('showAll\n')

    genfile.write('quit\n')

os.system('./gen.py')
